name: rolling

on:
  pull_request:
    branches:
      - rolling
  push:
    branches:
      - rolling
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    # Run in the ROS images of ros-tooling, with the same distributions as
    # the CoreSense Pixi channels
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-ros-${{ matrix.ros_distro }}-ros-base-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distro: [jazzy, kilted]
    steps:
      - uses: ros-tooling/action-ros-ci@0.4.8
        with:
          package-name: rossdl_cmake rossdl_simple_test system_a system_b application_1 application_2 application_3
          target-ros2-distro: ${{ matrix.ros_distro }}
          colcon-defaults: |
            {
              "test": {
                "parallel-workers" : 1
              }
            }
