name: rolling

on:
  pull_request:
    branches:
      - rolling
  push:
    branches:
      - rolling
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        ros_distro: [jazzy, kilted]
    steps:
      - uses: ros-tooling/setup-ros@0.7.19
        with:
          required-ros-distributions: ${{ matrix.ros_distro }}
      - uses: ros-tooling/action-ros-ci@0.4.8
        with:
          package-name: rossdl_cmake rossdl_simple_test system_a system_b application_1 application_2 application_3
          target-ros2-distro: ${{ matrix.ros_distro }}
          colcon-defaults: |
            {
              "test": {
                "parallel-workers" : 1
              }
            }
